### ISSUE TITLE
Module '"chai-spies"' has no exported member 'spies'.

### ISSUE THREAD

**Issue by JimLynchCodes** [chaijs/chai-spies#110]
When I enter this code in TypeScript it does not compile:
```
import { expect } from 'chai';
import { spies } from 'chai-spies';
chai.use(spies);
```

Error:` Module '"chai-spies"' has no exported member 'spies'.`

You should probably have a guide for TypeScript in the README. 

Thanks!
Jim

**Comment by keithamus** [comment]
Thanks for the issue @JimLynchCodes!

Right now you have to use the default export syntax; like so:

```js
import { expect } from 'chai';
import spies from 'chai-spies';
chai.use(spies);
```

Then to use it you call `chai.spy...`.

If you'd like to raise a PR to clarify the docs, we'd be super happy to review+merge it!

**Comment by JimLynchCodes** [comment]
Thanks @keithamus, you are a legend. 🙏

I have opened a PR here: https://github.com/chaijs/chai-spies/pull/111

❤️

**Comment by keithamus** [comment]
Thanks for raising a PR @JimLynchCodes! You're the legend here :)
