### ISSUE TITLE
Can't install with "bower install chai-spies"

### ISSUE THREAD

**Issue by KamilSzot** [chaijs/chai-spies#13]
Please consider packaging and publishing the plugin as bower package.

**Comment by christianhaller** [comment]
+

**Comment by lykmapipo** [comment]
+

**Comment by keithamus** [comment]
Thanks for the issue @KamilSzot, thanks for the upvotes @christianhaller and @lykmapipo.

I'm happy to merge a PR from any of you. It would be a case of creating the bower.json file and making sure it has the same info as the package.json & component.json. Once this is done, I'll merge it, and make a release (v0.5.2) and it'll be in bower.
