### ISSUE TITLE
bumping npm package version

### ISSUE THREAD

**Issue by d48** [chaijs/chai-spies#23]
Hello,

mind bumping up the npm package version with the latest commits? `chai.spy.on` is working great

**Comment by keithamus** [comment]
@logicalparadox - this one doesn't have a `.travis.yml` :smile:

**Comment by stalniy** [comment]
@keithamus any progress on this? 

Let me know if I can help you somehow.

**Comment by keithamus** [comment]
On my todo list for today, I'll get round to it later this afternoon :smile:

**Comment by d48** [comment]
:thumbsup:
