### ISSUE TITLE
`proxy.toString` blocks getting names of function parameters 

### ISSUE THREAD

**Issue by erykpiast** [chaijs/chai-spies#26]
I wonder if [this code](https://github.com/chaijs/chai-spies/blob/master/lib/spy.js#L64-L73) is really needed? I found that it breaks reading names of functions parameters ([like here](https://github.com/goatslacker/get-parameter-names)). I use some DI container that parses function definition string and because of that, I can test my modules only when I wrap spy in pure function.

``` javascript
let spy = chai.spy('justSpy');

annotatedFn(() => spy());

expect(spy).to.have.been.called.once();
```

So I can live with that, but I just wonder if anything can be improved.

**Comment by keithamus** [comment]
Hey @erykpiast thanks for the issue.

[get-parameter-names](https://github.com/goatslacker/get-parameter-names) is a huuuge hack, and the [Spec gives no guarantee that the function's toString() will return parameter names](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-function.prototype.tostring). This would be valid according to the spec:

  ```js
Function.prototype.toString = () => ':('
  ```

Therefore you cannot rely on the functionality of `Function.prototype.toString()`. 

On the other hand, the `proxy.toString()` method provides something that is useful within the test context which would be a shame to see go. Also, [we're not the only spies library that does this](https://github.com/cjohansen/Sinon.JS/blob/4f90794cb73f7c3cb412427547113a514c8b657f/test/sinon-test.js#L526-L552).

For these reasons, I feel like we're in a good place, and while I understand it might cause some frustrations - I think `proxy.toString()` is here to stay. As such, I'm going to close this issue. If you strongly disagree though, and want to continue to make a case for dropping it, please feel free to do so and I'll re-open the issue :smile:.

**Comment by erykpiast** [comment]
Hey, thank you for your response!

Of course, I know this method is really hacky, but, well, it's also very simple to use and comfortable ;) No need for annotations transpilers etc. ideal for testing purposes at least!

I really don't want to argue if you say this feature is essential, but could you show me, how anyone can benefit from that? I have no idea, really, and I'm really curious :D

**Comment by keithamus** [comment]
It is useful for diagnostics - whenever the Spy is logged, say, `console.log(myfn)` or within many inspection tools such as node's `util.inspect` - it will come up with the toString() value.

I guess we could have the best of both worlds, by making our `proxy.toString()` be something like:

```js
proxy.toString = function () {
    var l = this.__spy.call.length;
    return '// Spy ' + (this.__spy.name || '') + ', ' + l + 'call' + (l > 1 ? 's' : '') \n' + fn.toString();
}
```

That way we call the underlying functions toString(), but keep useful diagnostic information. For example:

```js
function Bar(bar) { return bar; }

let spy = chai.spy(Bar);

expect(spy.toString()).to.equal(
    `// Spy Bar, 0 calls
    function Bar(bar) { return bar; }`
);
```

Thoughts on this?

**Comment by erykpiast** [comment]
I guess it won't help arguments parsers at all (maybe with some modifications on their side...), but looks like a nice improvement for use cases you mentioned.

Anyway, interesting, I didn't even think that I can log entire function and get useful information during debugging!

**Comment by stalniy** [comment]
@keithamus what is the reasoning under to reopen this?

**Comment by keithamus** [comment]
@stalniy I think we could improve `spy.toString()` to be closer to what we have above; 

> 
```js
function Bar(bar) { return bar; }

let spy = chai.spy(Bar);

expect(spy.toString()).to.equal(
    `// Spy Bar, 0 calls
    function Bar(bar) { return bar; }`
);
```
