### ISSUE TITLE
method to reset spy object

### ISSUE THREAD

**Issue by d48** [chaijs/chai-spies#27]
Hello,

is there a method to reset a spy object for reuse? 

```
var boom = chai.spy(originalFn);

originalFn();

expect(boom).to.have.been.called.once;  // passes

boom.reset();

expect(boom).to.have.been.called.once;  //fails
```

Was helpful in another test framework and thought it would be great here. I can open up a pull request too if it's a matter of resetting some internal vars for the `callCount`

**Comment by keithamus** [comment]
Spies do not currently have a reset. I think it'd be a good idea to add one, and fairly simple to add.

Personally, I'd take the [existing metadata assignment (L74-L78)](https://github.com/chaijs/chai-spies/blob/master/lib/spy.js#L74-L78) and put it into the reset method, then call reset in the factory, so [L74-L80](https://github.com/chaijs/chai-spies/blob/master/lib/spy.js#L74-L80) look more like:

```js
    proxy.reset = function () {
        this.__spy = {
            calls: []
          , called: false
          , name: name
        };
        return this;
    }
    return proxy.reset();
```

Of course, if you were to make a PR, I'd expect some good test coverage to be present for this feature :smile:.

**Comment by d48** [comment]
fantastic! Let me see if I can get to this today

**Comment by d48** [comment]
PR #28 created, thanks

**Comment by d48** [comment]
Thanks @keithamus

**Comment by stalniy** [comment]
@d48 could you please describe a use case where you had a need in .reset() method?

**Comment by tamaserdfalvi** [comment]
Like if you have a mocked object and you're using the same instance of it for multiple test cases.

**Comment by stalniy** [comment]
The property of good tests is that it should start from clean state otherwise you can’t rely on results.

**Comment by mebibou** [comment]
I am coming from jasmine and really confused here, how would you test like this:
```
describe('myFunction', () => {
  describe('when another function returns true', () => {
    beforeEach(() => {
      chai.spy.on(class, 'anotherFunction', () => true);
    });

    it('should pass', () => {
      expect(myFunction()).to.equal(1);
    });
  });

  describe('when another function returns false', () => {
    beforeEach(() => {
      chai.spy.on(class, 'anotherFunction', () => false);
    });

    it('should not pass', () => {
      expect(myFunction()).to.equal(0);
    });
  });
});
```
but it tells me that the function is already a spy, even though the spies are not under the same `describe` (which totally works in jasmine thankfully)

**Comment by stalniy** [comment]
Jasmine automatically cleans up all spies in afterEach callback

What you need to do is to add

```js
afterEach()=>{
  chai.spy.restore(class, ‘anotherFunction')
})
```

**Comment by d48** [comment]
hi @stalniy, sure, I can answer a possible use case. It's a convenience method on your spy when making multiple calls to it that you can inspect, and maybe you want to reset after interacting with the spy.

And same as you just mentioned above, it can be used in an `afterEach` block to reuse if the spy is cached to a var
