### ISSUE TITLE
Bound functions

### ISSUE THREAD

**Issue by AlexanderTserkovniy** [chaijs/chai-spies#51]
Hey guys,

I have an issue during testing bound functions.

	// instanceName.onDisconnect = ... this.property = true ...
	// ...
	let spy = chai.spy.on(instanceName, 'onDisconnect');
	instanceName.connection.on('end'  , instanceName.onDisconnect.bind(instanceName));
	instanceName.connection.end();
	expect(instanceName.property).to.be.ok; // ok
	expect(spy).to.have.been.called(); // fail

	/* BUT IF! */

	let spy = chai.spy.on(instanceName, 'onDisconnect');
	instanceName.connection.on('end'  , () => instanceName.onDisconnect());
	instanceName.connection.end();
	expect(instanceName.property).to.be.ok; // ok
	expect(spy).to.have.been.called(); // ok

So as you can see from the example, if function is bound, then it fails, but if it is called directly, then it passes.

I think it is an issue.

Please advise, thanks.

**Comment by meeber** [comment]
@AlexanderTserkovniy Are you still having an issue with this? I haven't been able to reproduce the problem.

For example, this test passes:

```js
it("meep", () => {
  let instanceName = {
    connection: new EventEmitter(),
  };
  instanceName.onDisconnect = () => console.log("Disconnect!");

  let spy = chai.spy.on(instanceName, "onDisconnect");

  instanceName.connection.on("end", instanceName.onDisconnect.bind(instanceName));
  instanceName.connection.emit("end");

  expect(spy).to.have.been.called();
});
```

If you're still experiencing this issue, would you mind creating a minimal public repo demonstrating the problem in action? Thanks! :D

**Comment by AlexanderTserkovniy** [comment]
Currently cannot check as well as reproduce. Probably it is internal architecture issue. But thanks for checking and writing your response.

**Comment by meeber** [comment]
Sure thing. Feel free to re-open this issue if you run into it again.
