### ISSUE TITLE
What is the goal of chai-spies?

### ISSUE THREAD

**Issue by meeber** [chaijs/chai-spies#57]
The readme states up front that the primary purpose of chai-spies is to serve as an example of how to create a Chai plugin. This statement suggests that its role as a mocking library is secondary. It mentions that only the most basic of functionality is provided, and even goes so far as to recommend an alternative library if advanced functionality is desired.

Of course, just because those words were written `x` years ago doesn't mean they're true now, or that it's the way things should be going forward. However, as the Chai ecosystem grows and the number of maintainers increases, I think it's valuable to reach an understanding on what the goal of chai-spies is so that we're all of the right mindset when evaluating feature requests.

My opinion is that the originally stated goal and minimalistic scope of chai-spies should be strictly maintained, and that when it comes to users requesting advanced features, we should point them at sinon and chai-sinon. I think we do more good for the community overall by throwing our support behind these existing libraries rather than duplicating their efforts, and that chai-spies fulfills its own niche quite nicely as being super minimalistic.

With that said, I'll fall in line behind the popular opinion on this issue. Achieving clarity in the goal of chai-spies is more important to me than my opinion. But in that case I'd like to learn more about what the strengths of chai-spies are in comparison to sinon and sinon-chai, other than it being lightweight, so that we can work to maximize those strengths going forward.

**Comment by stalniy** [comment]
@keithamus @meeber probably I can share my vision of chai spies:
```html
Robust, easy to use library with nice chai integration
```
Few reasons why I don't like `sinon` to much terms with different methods (`stub`, `spy`, whatever), in order to use sinon you need to go through the whole docs and eventually you will not find answer to your question.

On the other hand `chai-spies` something intuitive, you dont need much docs. Just few methods. And then it's easy to guess like:
```js
const spy = chai.spy()
const returnFive = chai.spy.returns(5) // so, you write what you need: `spy returns 5` I haven't seen more obvious way to do it in js frameworks
const array = []
chai.spy.on(array, 'push') 
expect(array.push).not.to.have.been.called()

const interface = chai.spy.object({ run: null })
expect(interface.run).not.to.have.been.called()
```

Also I think the main goal of this ticket is to change README file to highlight this.

Does it make sense?

**Comment by keithamus** [comment]
@meeber do you have any thoughts on this?

**Comment by meeber** [comment]
I think it's clear that some people prefer chai-spies over sinon-chai, and that the features being requested recently can be implemented without sacrificing the qualities that make them prefer chai-spies. So, more power to this plugin!
