### ISSUE TITLE
chai.spy.on(...).returns

### ISSUE THREAD

**Issue by shellscape** [chaijs/chai-spies#62]
I mentioned in a comment on #39 that I'm migrating a large project from jasmine 1.x to mocha. I really want to avoid using sinon-chai and would much rather roll with pure chai goodness. Jasmine however, has a magical little call that's prolific in our test codebase:

```js
spyOn(object, 'method').andReturn(someValue);
```

Best I can tell, that's altogether missing from this lib. If there's a method I've missed, or there's a way to achieve the same, please do share it. I dare say it's not spelled out very clearly anywhere. But then I might be a big dummy.

Anyhow, this would be a grand feature to have.

**Comment by stalniy** [comment]
Currently you can do this (master branch)
```js
spy.on(obj, "method", returns => 5)
```

**Comment by stalniy** [comment]
In the nearest time 1.0.0 will be pushed with support for declarations like above + documentation. Thanks for using `chai-spies`!
