### ISSUE TITLE
How to spy on asynchronous calls

### ISSUE THREAD

**Issue by pronebird** [chaijs/chai-spies#64]
I have asynchronous mocha test with spied function being called many times with different parameters.

I'd like to verify the input on first and second calls, then complete the test case. How do you do that with chai-spies?

**Comment by cnexans** [comment]
We are trying to cover this feature on PR #75 .

**Comment by keithamus** [comment]
Hey @pronebird thanks for the issue.

As @cnexans mentions, #75 and #59 cover this. I'll close this one, but thanks for filing this issue and please don't hesitate to open any new ones if you find anything new!

**Comment by pronebird** [comment]
@cnexans @keithamus thank you for your efforts!
