### ISSUE TITLE
.to.have.been.called.with repeating params

### ISSUE THREAD

**Issue by olebokolo** [chaijs/chai-spies#69]
Hi, I am currently experiencing a strange issue with checking spies calls. It seems like it works only if checking calls with unique parameters, or I am using chai wrong which I would like to be pointed at.

To reproduce:

```
  it('checks spy calls with unique params', () => {
    const math = {
      multiply: function (a, b) {
        return a * b;
      }
    };

    const multiplyFunction = chai.spy.on(math, 'multiply');
    math.multiply(1, 2);
    chai.expect(multiplyFunction).to.have.been.called.with(1, 2);
  });


  it('checks spy calls with repeating params', () => {
    const math = {
      multiply: function (a, b) {
        return a * b;
      }
    };

    const multiplyFunction = chai.spy.on(math, 'multiply');
    math.multiply(1, 1);
    chai.expect(multiplyFunction).to.have.been.called.with(1, 1);
  });

```

First test always passes, while second fails, even if putting single 1 in expectation call params.
Here is the error message:

```
AssertionError: expected { Spy, 1 call } to have been called with [ 1, 1 ]
    at assertWith (node_modules\chai-spies\lib\spy.js:280:12)
    at assert (node_modules\chai\lib\chai\utils\addChainableMethod.js:84:49)
    at Context.<anonymous> (....test.ts:79:59)
    at tryCatcher (core\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (core\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (core\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (core\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (core\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (core\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (core\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (core\node_modules\bluebird\js\release\async.js:17:14)
```
Also multiplyFunction.__spy field does have a call with params 1, 1

```
"__spy":  {
    "calls": [
    [
      1,
      1
    ]
  ],
    "called": true
  }
```
Used versions: 
```
"@types/chai-spies": "0.0.0",
"chai": "^3.5.0",
"chai-as-promised": "^6.0.0",
"chai-spies": "^0.7.1",
```

**Comment by cnexans** [comment]
This seems to be an expected behavior of the actual algorithm that checks the call argument. I can add this fix to my fork and send the pull request if, of course, other contributors agree.

I'll soon take a look again to the algorithm and come back to you.

**Comment by stalniy** [comment]
You need to use `with.exactly` which will check order of args. 

Please close issue if that works for you

**Comment by olebokolo** [comment]
Thanks, using `.with.exactly(1, 1)` worked here, though I consider it a workaround rather than a solution of issue.

I still can't understand why `.with` assertion can't handle repeating params:

`
it('checks spy calls with unique params', () => {
    const object = {};
    const fooFunction = chai.spy.on(object, 'foo');
    object.foo(1, 2, 3);
    chai.expect(fooFunction).to.have.been.called.with(2);
  });

  it('checks spy calls with repeating params', () => {
    const object = {};
    const fooFunction = chai.spy.on(object, 'foo');
    object.foo(1, 2, 2);
    chai.expect(fooFunction).to.have.been.called.with(2);
  });
`

Second test fails while first one passes which isn't the obvious behavior IMHO. Yes I could use `.with.exactly` and check order of all three args, but I think the order isn't significant if I just want to check if number 2 appeared among function args.

**Comment by keithamus** [comment]
@olebokolo I would expect the tests in your original comment to pass. You say you have a patch? Please do send this over! `with` should handle repeating params.

**Comment by stalniy** [comment]
I guess similar fix was added in e13621b3d6f39805b33c7853105e9d097bbb50f6

**Comment by keithamus** [comment]
Yup! Looks like it. Let's cut a release now and @olebokolo can try and reproduce with chai spies 1.0.0

**Comment by stalniy** [comment]
1.0.0 released! Hooray!
