### ISSUE TITLE
expect(...).to.have.been.called.once is not a function

### ISSUE THREAD

**Issue by tindn** [chaijs/chai-spies#72]
chai version: 4.0.1
chai-spies version: 0.7.1 
Node.js version: 6.10.3

I upgraded chai and chair-spies and ran into the following error

`expect(spy).to.have.been.called.once()` fails with:

```
Unhandled rejection TypeError: expect(...).to.have.been.called.once is not a function
```

Would appreciate any help or direction on how to figure this issue out.

Thanks

**Comment by keithamus** [comment]
Hey @tindn thanks for the issue.

Taking a look at the [docs for `.once`](https://github.com/chaijs/chai-spies#once) - it is a property assertion, so you don't need the parens. In other words, you should use `expect(spy).to.have.been.called.once` not `expect(spy).to.have.been.called.once()`.

If you don't like that style you could always use `expect(spy).to.have.been.called(1)` or just `expect(spy).to.have.been.called()`.

I'll close this, as our documentation mentions all of this, and I don't think anything needs fixing here. Feel free to continue the discussion though!

**Comment by tindn** [comment]
thanks @keithamus. that fixed it.
