### ISSUE TITLE
chai-spies.js needs a rebuild on master

### ISSUE THREAD

**Issue by shellscape** [chaijs/chai-spies#76]
Come on folks, this one is a baddie. Because of the slow release cycle of this module, folks are depending on installing from `master` (which is bad enough in of itself). Please get this file up to date with the rest of the repo on master.

**Comment by shellscape** [comment]
And because it's been a few years since that file was updated, `folio` has since broken. The fix so that builds again is here: https://github.com/logicalparadox/folio/issues/4

**Comment by keithamus** [comment]
Hey @shellscape thanks for the issue.

If you'd like, please feel free to run a build of this package and submit a PR, I'll be happy to merge and publish 😄

**Comment by shellscape** [comment]
@keithamus I'm already tracking master changes [on this fork](https://github.com/shellscape/chai-spies) and publishing to [`chai-spies-next`](https://www.npmjs.com/package/chai-spies-next) because of the slow release cycle of the module. _Please_ feel free to cherry pick from that fork to get up to speed here in upstream.

I'm sympathetic to the amount of time open source projects take to maintain (especially since I joined with the webpack team for some of their repos - it's bananas), but with a very slow release cycle, oodles of people depending on master, long since dated files, and a broken build process,  perhaps a call for maintainers would be in order. It could really use some new ❤️ .

**Comment by keithamus** [comment]
@shellscape we are always happy to add new maintainers - typically after one or two successful PRs a contributor makes, we will bring them on as a maintainer to help with the project. 

If you would like, as you're maintaining the fork - I would be happy to add you as a maintainer to help build & push features through. I have very little time for coding or releasing but I'm always around to review PRs and work on the issue tracker.

**Comment by shellscape** [comment]
@keithamus I'd be happy to help the project out. But what's the publish path? Without a nimble way to publish new versions to NPM I'm not sure that it's time well spent (and I mean absolutely no disrespect by that).

**Comment by stalniy** [comment]
@keithamus what do you think if I replace `folio` with something more modern (e.g. `rollup` or `browserify`) and replace `Makefile` with `npm scripts`?

Then I will rebuild and send a PR

**Comment by shellscape** [comment]
rollup + npm script is a win.

**Comment by stalniy** [comment]
@keithamus what are the next steps for release to happen? Could you please define a milestone on github? So, I could understand and help to move things forward :)

Thanks!

**Comment by keithamus** [comment]
@stalniy if we're happy to release with the current state as-is, then we could make a PR to compile chai-spies.js, change the package.json version - then when merged we can tag the commit and make a release.
