### ISSUE TITLE
Switch logicalparadox refs to chaijs

### ISSUE THREAD

**Issue by mLuby** [chaijs/chai-spies#79]
At least three places reference the old repo: [logicalparadox/chai-spies](https://github.com/logicalparadox/chai-spies) which is a dead link.
1. [README.md](https://github.com/chaijs/chai-spies/search?utf8=%E2%9C%93&q=logicalparadox&type=)

2. [npmjs.com/chai-spies](https://www.npmjs.com/package/chai-spies) 

><img width="281" alt="screen shot 2017-08-30 at 12 55 34 pm" src="https://user-images.githubusercontent.com/2483420/29892319-0a164c3a-8d83-11e7-9b72-761230148d9c.png">

3. [chaijs.com/plugins/chai-spies](http://chaijs.com/plugins/chai-spies/)
><img width="270" alt="screen shot 2017-08-30 at 12 55 46 pm" src="https://user-images.githubusercontent.com/2483420/29892327-0d8c196c-8d83-11e7-8c67-f8e3a9c81441.png">

I'm happy to open a PR for 1 but I don't know where to fix 2 and 3.

**Comment by stalniy** [comment]
@keithamus any thoughts on this?

**Comment by stalniy** [comment]
meanwhile, @mLuby , could you please make a PR to fix README? 

@keithamus also I think it's time to release as `chai-spies` has not been released for 2 years :)

**Comment by keithamus** [comment]
yeah happy to cut a release of chai-spies. Let's get it in a good shape for a major version and release as 1.0.0 😄 

We can close this - the package.json reflects the up to date url, and when we cut a release the chai site is automatically updated. So there's no action on our part.

**Comment by mLuby** [comment]
@stalniy here's the tiny PR https://github.com/chaijs/chai-spies/pull/80
