### ISSUE TITLE
spy.interface documentation appears to be wrong

### ISSUE THREAD

**Issue by thaithcock** [chaijs/chai-spies#99]
Looking at the [interface documentation](https://github.com/chaijs/chai-spies#spyinterface) it seems to be slightly incorrect if you try and create an object through the array-of-keys syntax.

Particularly, it says you can do something like `chai.spy.interface(['on', 'off', 'emit']);`.

However, looking at the tests, there is no such expectation of being able to create an interface in that way. You need to pass a "base class" to create the interface from, like `chai.spy.interface("Object", ['on', 'off', 'emit']);`.

Creating an interface in the way the documentation suggests creates a weird object with integer keys, which is not quite what you want.

**Comment by stalniy** [comment]
Hi @thaithco 

This is a bug :) Thanks for raising this issue!

**Comment by jazzzz** [comment]
The documentation on [chaijs.com](https://www.chaijs.com/plugins/chai-spies/) is still not up to date, would it be possible to update it?
